services:
  database:
    image: postgres:16-alpine3.19
    ports:
      - 5432:5432
    volumes:
      - psql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=lucid
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
  mailer:
    image: axllent/mailpit:v1.16
    ports:
      - 1025:1025
      - 8025:8025
volumes:
  psql-data:
